# Generated by Django 6.1 on 2026-08-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_curso_codigo_alter_estudante_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('T', 'Trancada'), ('C', 'Cancelada'), ('F', 'Finalizada')], default='A', max_length=1),
        ),
    ]
